//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viscoin.Bot.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Viscoin.Bot.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///&apos;cigar&apos;,
        ///&apos;rebut&apos;,
        ///&apos;sissy&apos;,
        ///&apos;humph&apos;,
        ///&apos;awake&apos;,
        ///&apos;blush&apos;,
        ///&apos;focal&apos;,
        ///&apos;evade&apos;,
        ///&apos;naval&apos;,
        ///&apos;serve&apos;,
        ///&apos;heath&apos;,
        ///&apos;dwarf&apos;,
        ///&apos;model&apos;,
        ///&apos;karma&apos;,
        ///&apos;stink&apos;,
        ///&apos;grade&apos;,
        ///&apos;quiet&apos;,
        ///&apos;bench&apos;,
        ///&apos;abate&apos;,
        ///&apos;feign&apos;,
        ///&apos;major&apos;,
        ///&apos;death&apos;,
        ///&apos;fresh&apos;,
        ///&apos;crust&apos;,
        ///&apos;stool&apos;,
        ///&apos;colon&apos;,
        ///&apos;abase&apos;,
        ///&apos;marry&apos;,
        ///&apos;react&apos;,
        ///&apos;batty&apos;,
        ///&apos;pride&apos;,
        ///&apos;floss&apos;,
        ///&apos;helix&apos;,
        ///&apos;croak&apos;,
        ///&apos;staff&apos;,
        ///&apos;paper&apos;,
        ///&apos;unfed&apos;,
        ///&apos;whelp&apos;,
        ///&apos;trawl&apos;,
        ///&apos;outdo&apos;,
        ///&apos;adobe&apos;,
        ///&apos;crazy&apos;,
        ///&apos;sower&apos;,
        ///&apos;repay&apos;,
        ///&apos;digit&apos;,
        ///&apos;crate&apos;,
        ///&apos;cluck&apos;,
        ///&apos;spike&apos;,
        ///&apos;mimic&apos;,
        ///&apos;pound&apos;,
        ///&apos;maxim&apos;,....
        /// </summary>
        internal static string WordleItems {
            get {
                return ResourceManager.GetString("WordleItems", resourceCulture);
            }
        }
    }
}
